apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: retail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9-management
        ports:
        - containerPort: 5672   # AMQP
        - containerPort: 15672  # Management UI

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: retail
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
  - port: 15672
    targetPort: 15672
